package MVC.Model.DungeonItems.Items;

import MVC.Model.DungeonAdventure.DungeonCharacters.DungeonCharacter;
import MVC.Model.Physics.Vec2;

public class Bomb extends Item
{
    /**
     * Bomb constructor that calls its parent constructor to initialize its type and location.
     */
    protected Bomb() {
        super("Bomb", new Vec2());
    }

    /**
     * Bomb overloaded constructor that calls its parent constructor to initialize its type and location.
     * @param thePosition
     */
    protected Bomb(Vec2 thePosition) {
        super("Bomb", thePosition);
    }

    /**
     * This methods serves as the blast generated by a Bomb detonating when a DungeonCharacter enters a Room.
     * It reduces theCharacter's hit points by half.
     * @param theCharacter The DungeonCharacter whose hit points will be affected.
     */
    protected void blast(DungeonCharacter theCharacter)
    {
        theCharacter.setHitPoints(theCharacter.getHitPoints() / 2);
    }
}
