package MVC.Model.DungeonItems.Items;

import MVC.Model.DungeonAdventure.DungeonCharacters.DungeonCharacter;
import MVC.Model.Physics.Vec2;

public class Bomb extends Item
{
    /**
     * Bomb constructor that calls its parent constructor to initialize its type and location.
     */
    public Bomb() {
        super("Bomb", new Vec2());
    }



    //^^made these two constructors public for testing!!! they were protected ->>



    /**
     * Bomb overloaded constructor that calls its parent constructor to initialize its type and location.
     * @param thePosition The Bomb's location.
     */
    public Bomb(Vec2 thePosition) {
        super("Bomb", thePosition);
    }


    //made public for testing!!! was protected
    /**
     * This methods serves as the blast generated by a Bomb detonating when a DungeonCharacter enters a Room.
     * It reduces theCharacter's hit points by half.
     * @param theCharacter The DungeonCharacter whose hit points will be affected.
     */
    public void blast(DungeonCharacter theCharacter)
    {
        theCharacter.setHitPoints(theCharacter.getHitPoints() / 2);
    }
}
