package MVC.Model.DungeonItems.Items;

import MVC.Model.DungeonAdventure.DungeonCharacters.Hero;
import MVC.Model.Physics.Vec2;

public class Bomb extends Item
{
    /**
     * Bomb constructor that calls its parent constructor to initialize its type and location.
     */
    public Bomb() {
        super("Bomb");
    }

    /**
     * Bomb overloaded constructor that calls its parent constructor to initialize its type and location.
     * @param thePosition
     */
    protected Bomb(Vec2 thePosition) {
        super("Bomb");
    }

    /**
     * These methods serves as the blast generated by a Bomb detonating when a DungeonCharacter enters a Room.
     * It reduces theCharacter's hit points by half.
     * @param theHero The DungeonCharacter whose hit points will be affected.
     */
    @Override
    public void activate(Hero theHero)
    {
        theHero.setHitPoints(theHero.getHitPoints() / 2);
    }
}
